//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveFiles.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class Saveimg
    {
        public int ImgId { get; set; }


        public string ImgName { get; set; }

        [DisplayName("Upload File")]
        [Required(ErrorMessage = " Please Enter ImgPath")]
        public string ImgPath { get; set; }

        public HttpPostedFileBase UploadFile
        {
            get;set;
        

        }
    }
}
